// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgbtyigreyuuwnvltnub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnYnR5aWdyZXl1dXdudmx0bnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTMzMTMsImV4cCI6MjA3MjUyOTMxM30.QufimhSgsFgyzFB-FQZM6YmdBleFac3SOGaz3ez3MRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});