name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Create .env file
      run: |
        echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
        echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
    
    - name: Build web app
      run: npm run build
    
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli

    - name: Remove android folder if exists
      run: rm -rf android

    - name: Add Android platform
      run: npx cap add android
    
    - name: Generate Capacitor Resources
      run: |
        npm install -g @capacitor/assets
        npx capacitor-assets generate --android --iconBackgroundColor "#3b82f6" || echo "Skipping assets generation"
    
    - name: Sync Capacitor
      run: npx cap sync android
    
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon --stacktrace
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: KasirQ-POS-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
    
    - name: Get current date
      if: github.ref == 'refs/heads/main'
      id: date
      run: echo "date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
    
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}-${{ steps.date.outputs.date }}
        name: KasirQ POS v${{ github.run_number }}
        body: |
          🚀 **KasirQ POS Android APK**
          
          Build: #${{ github.run_number }}
          Date: ${{ steps.date.outputs.date }}
          Commit: ${{ github.sha }}
          
          ### Download
          Download file APK di bawah untuk install di Android
          
        files: |
          android/app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false